//
//  Strings.swift
//  Spy Hunter
//
//  Created by Roman Kavinskyi on 02.06.2020.
//  Copyright © 2020 Roman Kavinskyi. All rights reserved.
//

import Foundation

struct Strings {
    
    let addNewPlayer        = RKLocalizedString(key: "Enter title", comment: "Enter title and take photo")
    let error               = RKLocalizedString(key: "Error", comment: "Error occurred")
    let pressPlus           = RKLocalizedString(key: "Press Plus", comment: "Press plus to add new player")
    let next                = RKLocalizedString(key: "Next", comment: "Go next page")
    let back                = RKLocalizedString(key: "Back", comment: "Go back")
    let addOnePlayer        = RKLocalizedString(key: "Add Player", comment: "Add at least one player to continue")
    let deletePlayer        = RKLocalizedString(key: "Delete Player", comment: "Swipe left to delete the player")
    let standardLocations   = RKLocalizedString(key: "Standard Locations", comment: "Default Locations")
    let unusualLocations    = RKLocalizedString(key: "Unusual Locations", comment: "Unusual Locations")
    let locations           = RKLocalizedString(key: "Locations", comment: "Locations")
    let unavailable         = RKLocalizedString(key: "Unavailable", comment: "Unfortunately unavailable yet")
    let chooseOneLocation   = RKLocalizedString(key: "Choose One Location", comment: "Choose at least 1 location")
    let settings            = RKLocalizedString(key: "Settings", comment: "Settings")
    let start               = RKLocalizedString(key: "Start", comment: "Start")
    let hint                = RKLocalizedString(key: "Hint", comment: "It's better if every 4th player is a Spy")
    let understand          = RKLocalizedString(key: "Understand", comment: "I understand")
    let host                = RKLocalizedString(key: "Host", comment: "Someone is a host!")
    let showLocation        = RKLocalizedString(key: "Show Location", comment: "Show location")
    let passPhone           = RKLocalizedString(key: "Pass Phone", comment: "Please, pass phone to this player. Press on pictures to see your role.")
    let youSpy              = RKLocalizedString(key: "You are a spy", comment: "Your role is a spy")
    let spyHint             = RKLocalizedString(key: "Pretend you are not a spy. Try to guess the location to win", comment: "Pretend your not a spy")
    let locationIs          = RKLocalizedString(key: "Location is", comment: "It will reveal the location")
    let notSpyHint          = RKLocalizedString(key: "Ask questions about this place and reply but don't expose the location", comment: "self")
    let outOfTime           = RKLocalizedString(key: "Time's up", comment: "Out of time")
    let decideWhoSpy        = RKLocalizedString(key: "It's time to decide who is a spy", comment: "Discussion who is a spy")
    let showSpy             = RKLocalizedString(key: "Reveal Spies", comment: "Reveal spies")
    let playAgain           = RKLocalizedString(key: "Play again", comment: "Play one more time")
    let spiesAre            = RKLocalizedString(key: "Spies are:", comment: "Tells who is a spy")
    let spyIs               = RKLocalizedString(key: "Spy is:", comment: "Tells who is a spy")
    let discussionTime      = RKLocalizedString(key: "Discussion Time, min.", comment: "Discussion time in minutes")
    let numberOfSpies       = RKLocalizedString(key: "Number of Spies", comment: "Tim")
    let becomePro           = RKLocalizedString(key: "Become PRO player and access all the locations", comment: "App-in purchase")
    let players             = RKLocalizedString(key: "Players", comment: "Show's all the players")
    let save                = RKLocalizedString(key: "Save", comment: "Save changes")
    let textPlaceholder     = RKLocalizedString(key: "Enter player's name", comment: "Inputs player's name")
    let hospital            = RKLocalizedString(key: "Hospital", comment: "Hospital")
    let church              = RKLocalizedString(key: "Church", comment: "Church")
    let embassy             = RKLocalizedString(key: "Embassy", comment: "Embassy")
    let house               = RKLocalizedString(key: "House", comment: "House")
    let restaurant          = RKLocalizedString(key: "Restaurant", comment: "Restaurant")
    let cafe                = RKLocalizedString(key: "Cafe", comment: "Cafe")
    let factory             = RKLocalizedString(key: "Factory", comment: "Factory")
    let shop                = RKLocalizedString(key: "Shop", comment: "Shop")
    let flowersMarker       = RKLocalizedString(key: "Flower's Market", comment: "Flower's market")
    let bikeFixer           = RKLocalizedString(key: "Bike Service", comment: "Bike service")
    let gym                 = RKLocalizedString(key: "Gym", comment: "Gym")
    let bar                 = RKLocalizedString(key: "Bar", comment: "Bar")
    let park                = RKLocalizedString(key: "Park", comment: "Park")
    let garden              = RKLocalizedString(key: "Garden", comment: "Garden")
    let nightClub           = RKLocalizedString(key: "Night Club", comment: "Night Club")
    let castle              = RKLocalizedString(key: "Castle", comment: "Castle")
    let basement            = RKLocalizedString(key: "Basement", comment: "Basement")
    let bank                = RKLocalizedString(key: "Bank", comment: "Bank")
    let policeOffice        = RKLocalizedString(key: "Police Department", comment: "Police Department")
    let school              = RKLocalizedString(key: "School", comment: "School")
    let bakery              = RKLocalizedString(key: "Bakery", comment: "Bakery")
    let market              = RKLocalizedString(key: "Market", comment: "Market")
    let appleStore          = RKLocalizedString(key: "Apple Store", comment: "Apple Store")
    let mainSquare          = RKLocalizedString(key: "Main Square", comment: "Main Square")
    let marineBase          = RKLocalizedString(key: "Marine Base", comment: "Marine Base")
    let port                = RKLocalizedString(key: "Harbor", comment: "Harbor")
    let spaceStation        = RKLocalizedString(key: "Space Station", comment: "Space Station")
    let prison              = RKLocalizedString(key: "Prison", comment: "Prison")
    let artStudio           = RKLocalizedString(key: "Art Gallery", comment: "Art Gallery")
    let museum              = RKLocalizedString(key: "Museum", comment: "Museum")
    let architectureBureau  = RKLocalizedString(key: "Architecture Bureau", comment: "Architecture Bureau")
    let spaSalon            = RKLocalizedString(key: "SPA", comment: "SPA")
    let orphanage           = RKLocalizedString(key: "Orphanage", comment: "Orphanage")
    let parliament          = RKLocalizedString(key: "Parliament", comment: "Parliament")
    let metro               = RKLocalizedString(key: "Subway / Metro", comment: "Subway")
    let skyScrapper         = RKLocalizedString(key: "Sky Scrapper", comment: "Sky Scrapper")
    let polarStation        = RKLocalizedString(key: "Polar Station", comment: "Polar Station")
    let gameCenter          = RKLocalizedString(key: "Game Center", comment: "Game Center")
    let university          = RKLocalizedString(key: "University", comment: "University")
    let plane               = RKLocalizedString(key: "Airplane", comment: "Airplane")
    let mine                = RKLocalizedString(key: "Mine", comment: "Mine")
    let island              = RKLocalizedString(key: "Island", comment: "Island")
    let zoo                 = RKLocalizedString(key: "Zoo", comment: "Zoo")
    let submarine           = RKLocalizedString(key: "Submarine", comment: "Submarine")
    let observationDeck     = RKLocalizedString(key: "Observation Deck", comment: "Observation Deck")
    let cave                = RKLocalizedString(key: "Cave", comment: "Cave")
    let beach               = RKLocalizedString(key: "Beach", comment: "Beach")
    let festival            = RKLocalizedString(key: "Festival", comment: "Festival")
    let instructions        = RKLocalizedString(key: "All players should be in a circle facing each other. The game starts by the host. \n \n The host reads instructions and passes the device to the next player. Each player will either see the location or receive a SPY role. It's forbidden to name the location during the game", comment: "self")
    let rules               = RKLocalizedString(key: "Rules", comment: "Game Rules")
    let generalLabelText    = RKLocalizedString(key: "In this game each player will play one of two possible roles i.e. SPY or civilian. The goal of the game depends on your role. The SPY will attempt to gather information to identify a location, and the civilians will be given a location and will try to find the SPY in the group. You need a minimum of three players to start the game and it ends when the discussions are over and the players try to guess who the SPY is by voting. If the SPY is identified, they win, however - if they are wrong, they lose. At any stage of the game, the SPY can guess the secret location in an attempt to win the game, however, if the SPY is wrong, the civilians win.", comment: "self")
    let discussion          = RKLocalizedString(key: "The discussion starts with a host. He'll ask a question about the location to the next player clockwise or counterclockwise. The player which have answered the question continues to ask in the given direction. After all players've answered the question and it's host's turn to ask again he is free to ask whatever player he wants. The player answers the question and as well can ask whatever player he wants. The player cannot be asked twice in a row", comment: "self")
    let discussionTitle     = RKLocalizedString(key: "Discussion:", comment: "Discussion")
    let votingTitle         = RKLocalizedString(key: "Voting:", comment: "Voting")
    let votingText          = RKLocalizedString(key: "After the discussion all players should debate who they think is a spy. The decision is made by the player's majority. If player who has been chosen is not a spy - real spy wins. The spy can name the location during this time. If spy is correct he wins if not he looses.", comment: "self")
    let playersTitle        = RKLocalizedString(key: "All players", comment: "Players in the database")
    let becomeProTitle      = RKLocalizedString(key: "Become Pro", comment: "Buy premium")
    let discussionIsOver    = RKLocalizedString(key: "Discussion time is over! Who's the SPY?", comment: "self")
    let timeIsUp            = RKLocalizedString(key: "Time's up!", comment: "Time finished")
    
    let harryPotterLocs     = RKLocalizedString(key: "Harry Potter Locations", comment: "self")
    let theBurrow           = RKLocalizedString(key: "The Burrow", comment: "Harry Potter. The Weasley's house.")
    let godricHollow        = RKLocalizedString(key: "Godric's Hollow", comment: "Harry Potter. Village where Lily and James Potter lived.")
    let littleHangleton     = RKLocalizedString(key: "Little Hangleton", comment: "Harry Potter. Lord Voldemort's home village and place where he resurected in Harry Potter and Goblet of Fire.")
    let littleWhinging      = RKLocalizedString(key: "Little Whinging", comment: "Harry Potter. Town where Harry lived with Dursleys.")
    let malfoyManor         = RKLocalizedString(key: "Malfoy Manor", comment: "Home of Malfoy family.")
    let number12            = RKLocalizedString(key: "12, Grimmauld Place", comment: "The address of the London's home of Black Family, that was Order of the Phoenix's headquarters.")
    let beauxbatons         = RKLocalizedString(key: "Beauxbatons Academy", comment: "Magic school in France.")
    let durmstrang          = RKLocalizedString(key: "Durmstrang Institute", comment: "Magic school in Scandinavia.")
    let hogwarts            = RKLocalizedString(key: "Hogwarts", comment: "Magic school where Harry Potter studied.")
    let ilvermorny          = RKLocalizedString(key: "Ilvermorny School", comment: "Magic school location in the US.")
    let diagonAlley         = RKLocalizedString(key: "Diagon Alley", comment: "A magical street location in London")
    let gringotts           = RKLocalizedString(key: "Gringotts Bank", comment: "Magical Bank")
    let ollivanders         = RKLocalizedString(key: "Ollivanders", comment: "A wand shop.")
    let hogsmeade           = RKLocalizedString(key: "Hogsmeade Vallage", comment: "The only settelment in Britain inhavited by solely wizards.")
    let threeBroomsticks    = RKLocalizedString(key: "The Three Broomsticks", comment: "A well known pub located in Hogsmeade")
    let hogsHead            = RKLocalizedString(key: "The Hog's Head", comment: "Another pub in Hogsmeade that attracts disreputable clientele.")
    let hogsmeadeStation    = RKLocalizedString(key: "Hogsmeade Station", comment: "Hogsmeade Station is the closest train stop to Hogwarts; the Hogwarts Express stops here after travelling from King's Cross.")
    let azkaban             = RKLocalizedString(key: "Azkaban", comment: "A magical prizon.")
    let ministry            = RKLocalizedString(key: "Ministry of Magic", comment: "The Ministry of Magic is the government of the Magical community of Britain.")
    let magicalHospital     = RKLocalizedString(key: "St Mungo's Hospital", comment: "St Mungo's Hospital for Magical Maladies and Injuries is a hospital within the Harry Potter universe.")
    let nurmengard          = RKLocalizedString(key: "Nurmengard", comment: "Nurmengard is the prison that Gellert Grindelwald built to keep his enemies and Muggles in.")
    let platform            = RKLocalizedString(key: "The Platform ​9¾", comment: "The ride on the Hogwarts Express starts from King's Cross railway station platform ​9 3⁄4, which is hidden from view, and reached by walking through the barrier between platforms 9 and 10.")
    let privetDrive         = RKLocalizedString(key: "Privet Drive", comment: "The street where Harry lived with Dursleys")
    
    let willow              = RKLocalizedString(key: "Whomping willow", comment: "The willow at the Hogwarts school, which has a secret way to Hogsmease")
    
    let lotrPlaces          = RKLocalizedString(key: "Lord of the Rings Locations", comment: "self")
    let shire               = RKLocalizedString(key: "The Shire", comment: "Place where hobbits are from")
    let eriador             = RKLocalizedString(key: "Eriador", comment: "Large region of free people to the west of Misty Mountains")
    let rivendell           = RKLocalizedString(key: "Rivendell", comment: "Elven town on the eastern edge of Eriador")
    let bree                = RKLocalizedString(key: "Bree", comment: "Human town in Eriador")
    let weathertop          = RKLocalizedString(key: "Weathertop", comment: "The top of Weather Hills.")
    let amonsul             = RKLocalizedString(key: "Amon Sul", comment: "The destroyed tower on the top of Weathertop")
    let valinor             = RKLocalizedString(key: "Valinor", comment: "The land on the other side of the great ocean.")
    let moria               = RKLocalizedString(key: "Moria", comment: "Abandoned dwarf's kingdom under the Misty Mountains.")
    let fangorn             = RKLocalizedString(key: "Fangorn Forest", comment: "The forest that is a habitat of Ents.")
    let isengard            = RKLocalizedString(key: "Isengard", comment: "self")
    let rohan               = RKLocalizedString(key: "Rohan", comment: "self")
    let gondor              = RKLocalizedString(key: "Gondor", comment: "self")
    let anduin              = RKLocalizedString(key: "The Great River / Anduin", comment: "Very long river that goes from north to south of the continent")
    let minasTirith         = RKLocalizedString(key: "Minas Tirith", comment: "A great fortress, the last stand of the mankind, right next to the Mordor")
    let mordor              = RKLocalizedString(key: "Mordor", comment: "self")
    let baradDur            = RKLocalizedString(key: "Barad-dur", comment: "The dark tower in Mordor")
    let erebor              = RKLocalizedString(key: "The Lonely Mountain / Erebor", comment: "self")
    let mistyMountains      = RKLocalizedString(key: "Misty Mountains", comment: "self")
    let helmsDeep           = RKLocalizedString(key: "Helm's Deep", comment: "The place in Rohan where Rohan people always won fights.")
    let lorian              = RKLocalizedString(key: "Lórian", comment: "Elvish kingdom")
    let mountDoom           = RKLocalizedString(key: "Mount Doom", comment: "A mount from which fire the One Ring was forged.")
    let numenor             = RKLocalizedString(key: "Númenor", comment: "An island given to Edain as recognition of their valor in the war against Morgoth")
    let harad               = RKLocalizedString(key: "Harad", comment: "The location to the south from Gondor and Mordor.")
    let angmar              = RKLocalizedString(key: "Angmar", comment: "Land of the Which-King.")
    let cirithUngol         = RKLocalizedString(key: "Cirith Ungol", comment: "The shortest way to Mordor")
    let dolGuldur           = RKLocalizedString(key: "Dol Guldur", comment: "Sauron's stronghold and base of operations while secretly regaining his power as The Necromancer")
    
    let gameOfThrones       = RKLocalizedString(key: "Game of Thrones", comment: "self")
    let bravos              = RKLocalizedString(key: "Bravos", comment: "City of Bravos")
    let theEyrie            = RKLocalizedString(key: "The Eyrie", comment: "Eagle's nest")
    let casterly            = RKLocalizedString(key: "Casterly Rock", comment: "Lanister's castle")
    let kingsLanding        = RKLocalizedString(key: "King's Landing", comment: "Capital of 7 Kingdoms")
    let dragonstone         = RKLocalizedString(key: "Dragonstone", comment: "Dayneris weas orn there")
    let theIronIslands      = RKLocalizedString(key: "The Iron Islands", comment: "What's dead cannot die")
    let meereen             = RKLocalizedString(key: "Meereen", comment: "The Free City with Pyramids.")
    let oldTown             = RKLocalizedString(key: "Old Town", comment: "A city with rich library")
    let qarth               = RKLocalizedString(key: "Qarth", comment: "Free City with warlock")
    let riverrun            = RKLocalizedString(key: "Riverrun", comment: "Catelyn Stark Hometown")
    let hardhome            = RKLocalizedString(key: "Hardhome", comment: "City beyond the wall")
    let theTwins            = RKLocalizedString(key: "The Twins", comment: "The place of bloody wedding")
    let dothrak             = RKLocalizedString(key: "Vaes Dothrak", comment: "Biggest city of Dothrak")
    let winterfell          = RKLocalizedString(key: "Winterfell", comment: "self")
    let valyria             = RKLocalizedString(key: "Valyria", comment: "Ancient capital of Essos")
    let theWall             = RKLocalizedString(key: "The Wall", comment: "self")
    let valantis            = RKLocalizedString(key: "Valantis", comment: "The colony of Valyria the tried to become a new capital")
    let hallOfFaces         = RKLocalizedString(key: "Hall of Faces", comment: "Place where Aria learned to change appearance")
    let highgarden          = RKLocalizedString(key: "Highgarden", comment: "self")
    let walkOfShame         = RKLocalizedString(key: "Walk of Shame", comment: "self")
    let castleBlack         = RKLocalizedString(key: "Castle Black", comment: "A Fortress next to The Wall")
    let whiteHarbor         = RKLocalizedString(key: "White Harbor", comment: "self")
    let naath               = RKLocalizedString(key: "Naath", comment: "The island where Missandia is from")
    let dorne               = RKLocalizedString(key: "Dorne", comment: "self")
    let restore             = RKLocalizedString(key: "Restore", comment: "Restore purchases")
    let done                = RKLocalizedString(key: "All set", comment: "self")
    let restoted            = RKLocalizedString(key: "Your purchases has been restored", comment: "self")
}




//"Всі гравці мають сиділи в в колі, обличчям один до одного. Починає гру ведучий. \n \nВін читатиме інструкції та передасть девайс наступному гравцю. Кожен гравець побачить або локацію, або ж дізнається що він шпіон. Під час кола обговорень не можна називати локацію"

//"Для гри потрібно як мінімум 3 гравця. Кожен гравець або знатиме локацію, або ж буде шпіоном. Задача гравців своїми запитання та відповідями не видати локацію, а задача шпіона не видати, що він шпіон. Після кола обговореня гравці голосують, хто, як вони вважають, шпіон. Якщо шпіон відгадує локацію - виграє він."

//"Коло обговорення починає ведучий, задаючи питання про локацію наступному гравцю по годинниковій, або ж проти годинникової стрілки. Гравець який відповів на запитання продовжує питати в тому ж напрямку. Коли всі гравці в кругу відповіли і черга задавати питання вернулась до ведучого, він може задати питання будь якому гравцю. Після цього гравець, який відповів, задає питання гравцю на свій вибір. Не можна запитувати одного і того ж гравця підряд."

//"Після кола обговорень гравці радяться, та вирішують хто шпіон. Рішення приймається більшістю. За цей час шпіон має шанс назвати локацію та виграти. Якщо шпіон називає локацію, проте помиляється - він програє."
