//
//  StylishSpy.swift
//  SpyHunter
//
//  Created by Roman Kavinskyi on 25.05.2020.
//  Copyright © 2020 RT. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//
//  This code was generated by Trial version of PaintCode, therefore cannot be used for commercial purposes.
//



import UIKit

public class StylishSpy : NSObject {

    //// Drawing Methods

    @objc dynamic public class func drawCanvas1(frame targetFrame: CGRect = CGRect(x: 0, y: 0, width: 1958, height: 3559), resizing: ResizingBehavior = .aspectFit) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        
        //// Resize to Target Frame
        context.saveGState()
        let resizedFrame: CGRect = resizing.apply(rect: CGRect(x: 0, y: 0, width: 1958, height: 3559), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 1958, y: resizedFrame.height / 3559)


        //// Color Declarations
        let fillColor = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)

        //// Group 2
        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.move(to: CGPoint(x: 835.71, y: 0.74))
        bezierPath.addCurve(to: CGPoint(x: 673.11, y: 25.94), controlPoint1: CGPoint(x: 777.96, y: 2.62), controlPoint2: CGPoint(x: 717.28, y: 12.07))
        bezierPath.addCurve(to: CGPoint(x: 513.28, y: 278.54), controlPoint1: CGPoint(x: 605.53, y: 47.17), controlPoint2: CGPoint(x: 552.43, y: 131.09))
        bezierPath.addCurve(to: CGPoint(x: 479.98, y: 447.44), controlPoint1: CGPoint(x: 500.83, y: 325.49), controlPoint2: CGPoint(x: 488.61, y: 387.59))
        bezierPath.addCurve(to: CGPoint(x: 476.68, y: 467.54), controlPoint1: CGPoint(x: 478.41, y: 458.32), controlPoint2: CGPoint(x: 476.91, y: 467.32))
        bezierPath.addCurve(to: CGPoint(x: 464.01, y: 469.79), controlPoint1: CGPoint(x: 476.46, y: 467.77), controlPoint2: CGPoint(x: 470.76, y: 468.82))
        bezierPath.addCurve(to: CGPoint(x: 288.58, y: 515.32), controlPoint1: CGPoint(x: 401.68, y: 479.17), controlPoint2: CGPoint(x: 337.11, y: 495.89))
        bezierPath.addCurve(to: CGPoint(x: 236.31, y: 540.37), controlPoint1: CGPoint(x: 273.66, y: 521.24), controlPoint2: CGPoint(x: 247.26, y: 533.92))
        bezierPath.addCurve(to: CGPoint(x: 191.01, y: 574.34), controlPoint1: CGPoint(x: 217.86, y: 551.17), controlPoint2: CGPoint(x: 203.23, y: 562.19))
        bezierPath.addCurve(to: CGPoint(x: 157.11, y: 648.67), controlPoint1: CGPoint(x: 167.61, y: 597.82), controlPoint2: CGPoint(x: 157.11, y: 620.77))
        bezierPath.addCurve(to: CGPoint(x: 192.51, y: 737.54), controlPoint1: CGPoint(x: 157.11, y: 677.47), controlPoint2: CGPoint(x: 168.06, y: 704.92))
        bezierPath.addCurve(to: CGPoint(x: 419.83, y: 869.17), controlPoint1: CGPoint(x: 229.63, y: 787.04), controlPoint2: CGPoint(x: 302.61, y: 829.34))
        bezierPath.addLine(to: CGPoint(x: 443.46, y: 877.27))
        bezierPath.addLine(to: CGPoint(x: 446.98, y: 892.27))
        bezierPath.addCurve(to: CGPoint(x: 473.98, y: 967.12), controlPoint1: CGPoint(x: 455.16, y: 927.22), controlPoint2: CGPoint(x: 461.38, y: 944.54))
        bezierPath.addCurve(to: CGPoint(x: 516.96, y: 1191.29), controlPoint1: CGPoint(x: 503.01, y: 1019.32), controlPoint2: CGPoint(x: 516.96, y: 1091.99))
        bezierPath.addCurve(to: CGPoint(x: 515.98, y: 1236.67), controlPoint1: CGPoint(x: 516.96, y: 1210.64), controlPoint2: CGPoint(x: 516.51, y: 1229.39))
        bezierPath.addCurve(to: CGPoint(x: 491.01, y: 1379.84), controlPoint1: CGPoint(x: 511.93, y: 1289.92), controlPoint2: CGPoint(x: 504.43, y: 1333.04))
        bezierPath.addCurve(to: CGPoint(x: 462.96, y: 1435.42), controlPoint1: CGPoint(x: 482.68, y: 1408.94), controlPoint2: CGPoint(x: 475.71, y: 1422.82))
        bezierPath.addCurve(to: CGPoint(x: 465.81, y: 1454.47), controlPoint1: CGPoint(x: 455.16, y: 1443.14), controlPoint2: CGPoint(x: 455.16, y: 1443.07))
        bezierPath.addCurve(to: CGPoint(x: 489.66, y: 1481.92), controlPoint1: CGPoint(x: 476.68, y: 1466.17), controlPoint2: CGPoint(x: 483.51, y: 1473.97))
        bezierPath.addCurve(to: CGPoint(x: 503.83, y: 1502.17), controlPoint1: CGPoint(x: 495.96, y: 1490.02), controlPoint2: CGPoint(x: 503.83, y: 1501.27))
        bezierPath.addCurve(to: CGPoint(x: 494.46, y: 1495.57), controlPoint1: CGPoint(x: 503.83, y: 1502.54), controlPoint2: CGPoint(x: 499.63, y: 1499.62))
        bezierPath.addCurve(to: CGPoint(x: 481.86, y: 1485.89), controlPoint1: CGPoint(x: 489.28, y: 1491.59), controlPoint2: CGPoint(x: 483.58, y: 1487.17))
        bezierPath.addCurve(to: CGPoint(x: 473.31, y: 1482.14), controlPoint1: CGPoint(x: 478.63, y: 1483.42), controlPoint2: CGPoint(x: 474.06, y: 1481.47))
        bezierPath.addCurve(to: CGPoint(x: 478.93, y: 1498.19), controlPoint1: CGPoint(x: 473.08, y: 1482.37), controlPoint2: CGPoint(x: 475.63, y: 1489.57))
        bezierPath.addCurve(to: CGPoint(x: 495.58, y: 1550.47), controlPoint1: CGPoint(x: 486.73, y: 1518.44), controlPoint2: CGPoint(x: 491.01, y: 1532.02))
        bezierPath.addCurve(to: CGPoint(x: 507.58, y: 1653.82), controlPoint1: CGPoint(x: 503.98, y: 1584.22), controlPoint2: CGPoint(x: 507.58, y: 1615.34))
        bezierPath.addCurve(to: CGPoint(x: 501.43, y: 1735.42), controlPoint1: CGPoint(x: 507.58, y: 1682.77), controlPoint2: CGPoint(x: 505.93, y: 1704.89))
        bezierPath.addCurve(to: CGPoint(x: 498.96, y: 1765.79), controlPoint1: CGPoint(x: 499.41, y: 1749.07), controlPoint2: CGPoint(x: 499.03, y: 1753.72))
        bezierPath.addCurve(to: CGPoint(x: 507.58, y: 1807.79), controlPoint1: CGPoint(x: 498.96, y: 1784.17), controlPoint2: CGPoint(x: 500.76, y: 1793.09))
        bezierPath.addCurve(to: CGPoint(x: 518.46, y: 1834.42), controlPoint1: CGPoint(x: 510.66, y: 1814.39), controlPoint2: CGPoint(x: 518.83, y: 1834.42))
        bezierPath.addCurve(to: CGPoint(x: 507.66, y: 1821.67), controlPoint1: CGPoint(x: 518.31, y: 1834.42), controlPoint2: CGPoint(x: 513.43, y: 1828.64))
        bezierPath.addCurve(to: CGPoint(x: 496.33, y: 1808.92), controlPoint1: CGPoint(x: 501.81, y: 1814.69), controlPoint2: CGPoint(x: 496.71, y: 1808.92))
        bezierPath.addCurve(to: CGPoint(x: 494.68, y: 1810.79), controlPoint1: CGPoint(x: 495.88, y: 1808.92), controlPoint2: CGPoint(x: 495.21, y: 1809.74))
        bezierPath.addCurve(to: CGPoint(x: 499.41, y: 1838.32), controlPoint1: CGPoint(x: 493.78, y: 1812.82), controlPoint2: CGPoint(x: 495.36, y: 1822.19))
        bezierPath.addCurve(to: CGPoint(x: 535.11, y: 1932.67), controlPoint1: CGPoint(x: 506.08, y: 1865.09), controlPoint2: CGPoint(x: 519.58, y: 1900.87))
        bezierPath.addCurve(to: CGPoint(x: 540.88, y: 1947.29), controlPoint1: CGPoint(x: 539.01, y: 1940.62), controlPoint2: CGPoint(x: 540.81, y: 1945.27))
        bezierPath.addCurve(to: CGPoint(x: 565.63, y: 1987.57), controlPoint1: CGPoint(x: 541.11, y: 1953.29), controlPoint2: CGPoint(x: 552.51, y: 1971.89))
        bezierPath.addCurve(to: CGPoint(x: 751.71, y: 2107.34), controlPoint1: CGPoint(x: 604.18, y: 2033.69), controlPoint2: CGPoint(x: 668.38, y: 2075.02))
        bezierPath.addCurve(to: CGPoint(x: 872.08, y: 2146.42), controlPoint1: CGPoint(x: 772.48, y: 2115.44), controlPoint2: CGPoint(x: 847.11, y: 2139.67))
        bezierPath.addCurve(to: CGPoint(x: 958.71, y: 2164.04), controlPoint1: CGPoint(x: 897.51, y: 2153.32), controlPoint2: CGPoint(x: 944.16, y: 2162.84))
        bezierPath.addCurve(to: CGPoint(x: 998.08, y: 2159.47), controlPoint1: CGPoint(x: 965.46, y: 2164.64), controlPoint2: CGPoint(x: 973.56, y: 2163.67))
        bezierPath.addCurve(to: CGPoint(x: 1095.96, y: 2134.49), controlPoint1: CGPoint(x: 1032.73, y: 2153.54), controlPoint2: CGPoint(x: 1067.68, y: 2144.62))
        bezierPath.addCurve(to: CGPoint(x: 1217.46, y: 2084.54), controlPoint1: CGPoint(x: 1154.91, y: 2113.42), controlPoint2: CGPoint(x: 1184.01, y: 2101.49))
        bezierPath.addCurve(to: CGPoint(x: 1301.46, y: 2033.54), controlPoint1: CGPoint(x: 1249.18, y: 2068.49), controlPoint2: CGPoint(x: 1269.81, y: 2055.97))
        bezierPath.addCurve(to: CGPoint(x: 1343.01, y: 2000.47), controlPoint1: CGPoint(x: 1326.28, y: 2015.92), controlPoint2: CGPoint(x: 1339.93, y: 2005.04))
        bezierPath.addCurve(to: CGPoint(x: 1357.41, y: 1985.32), controlPoint1: CGPoint(x: 1346.31, y: 1995.44), controlPoint2: CGPoint(x: 1356.81, y: 1984.34))
        bezierPath.addCurve(to: CGPoint(x: 1362.28, y: 1980.29), controlPoint1: CGPoint(x: 1357.71, y: 1985.69), controlPoint2: CGPoint(x: 1359.88, y: 1983.44))
        bezierPath.addCurve(to: CGPoint(x: 1372.26, y: 1967.62), controlPoint1: CGPoint(x: 1364.76, y: 1977.07), controlPoint2: CGPoint(x: 1369.18, y: 1971.37))
        bezierPath.addCurve(to: CGPoint(x: 1394.01, y: 1938.37), controlPoint1: CGPoint(x: 1380.66, y: 1957.27), controlPoint2: CGPoint(x: 1388.01, y: 1947.44))
        bezierPath.addLine(to: CGPoint(x: 1399.48, y: 1930.27))
        bezierPath.addLine(to: CGPoint(x: 1398.21, y: 1927.87))
        bezierPath.addCurve(to: CGPoint(x: 1401.43, y: 1916.17), controlPoint1: CGPoint(x: 1397.01, y: 1925.54), controlPoint2: CGPoint(x: 1397.01, y: 1925.54))
        bezierPath.addCurve(to: CGPoint(x: 1433.08, y: 1822.94), controlPoint1: CGPoint(x: 1413.36, y: 1891.19), controlPoint2: CGPoint(x: 1424.61, y: 1858.12))
        bezierPath.addCurve(to: CGPoint(x: 1434.81, y: 1809.82), controlPoint1: CGPoint(x: 1435.78, y: 1811.77), controlPoint2: CGPoint(x: 1435.93, y: 1810.72))
        bezierPath.addCurve(to: CGPoint(x: 1432.71, y: 1808.92), controlPoint1: CGPoint(x: 1434.13, y: 1809.37), controlPoint2: CGPoint(x: 1433.16, y: 1808.92))
        bezierPath.addCurve(to: CGPoint(x: 1421.83, y: 1820.92), controlPoint1: CGPoint(x: 1432.18, y: 1808.92), controlPoint2: CGPoint(x: 1427.31, y: 1814.32))
        bezierPath.addCurve(to: CGPoint(x: 1411.63, y: 1832.69), controlPoint1: CGPoint(x: 1416.36, y: 1827.52), controlPoint2: CGPoint(x: 1411.71, y: 1832.84))
        bezierPath.addCurve(to: CGPoint(x: 1417.63, y: 1816.34), controlPoint1: CGPoint(x: 1411.48, y: 1832.54), controlPoint2: CGPoint(x: 1414.18, y: 1825.19))
        bezierPath.addCurve(to: CGPoint(x: 1431.58, y: 1776.29), controlPoint1: CGPoint(x: 1427.23, y: 1791.82), controlPoint2: CGPoint(x: 1430.68, y: 1781.84))
        bezierPath.addCurve(to: CGPoint(x: 1429.41, y: 1751.24), controlPoint1: CGPoint(x: 1432.33, y: 1771.79), controlPoint2: CGPoint(x: 1432.11, y: 1769.17))
        bezierPath.addCurve(to: CGPoint(x: 1421.53, y: 1656.29), controlPoint1: CGPoint(x: 1423.33, y: 1710.52), controlPoint2: CGPoint(x: 1421.46, y: 1688.77))
        bezierPath.addCurve(to: CGPoint(x: 1425.66, y: 1592.17), controlPoint1: CGPoint(x: 1421.53, y: 1629.82), controlPoint2: CGPoint(x: 1422.51, y: 1614.89))
        bezierPath.addCurve(to: CGPoint(x: 1451.46, y: 1494.37), controlPoint1: CGPoint(x: 1430.38, y: 1557.82), controlPoint2: CGPoint(x: 1439.61, y: 1522.79))
        bezierPath.addCurve(to: CGPoint(x: 1453.78, y: 1481.92), controlPoint1: CGPoint(x: 1455.36, y: 1484.92), controlPoint2: CGPoint(x: 1455.96, y: 1481.92))
        bezierPath.addCurve(to: CGPoint(x: 1438.33, y: 1492.49), controlPoint1: CGPoint(x: 1452.28, y: 1481.92), controlPoint2: CGPoint(x: 1446.73, y: 1485.74))
        bezierPath.addCurve(to: CGPoint(x: 1427.53, y: 1500.97), controlPoint1: CGPoint(x: 1433.98, y: 1495.94), controlPoint2: CGPoint(x: 1429.11, y: 1499.77))
        bezierPath.addLine(to: CGPoint(x: 1424.61, y: 1503.14))
        bezierPath.addLine(to: CGPoint(x: 1426.26, y: 1500.22))
        bezierPath.addCurve(to: CGPoint(x: 1460.61, y: 1457.09), controlPoint1: CGPoint(x: 1431.81, y: 1490.39), controlPoint2: CGPoint(x: 1447.11, y: 1471.19))
        bezierPath.addCurve(to: CGPoint(x: 1465.26, y: 1434.44), controlPoint1: CGPoint(x: 1474.18, y: 1442.99), controlPoint2: CGPoint(x: 1474.11, y: 1443.29))
        bezierPath.addCurve(to: CGPoint(x: 1438.48, y: 1381.42), controlPoint1: CGPoint(x: 1452.36, y: 1421.39), controlPoint2: CGPoint(x: 1446.28, y: 1409.24))
        bezierPath.addCurve(to: CGPoint(x: 1412.01, y: 1212.67), controlPoint1: CGPoint(x: 1422.66, y: 1324.79), controlPoint2: CGPoint(x: 1414.78, y: 1274.62))
        bezierPath.addCurve(to: CGPoint(x: 1422.96, y: 1077.22), controlPoint1: CGPoint(x: 1410.13, y: 1169.17), controlPoint2: CGPoint(x: 1413.43, y: 1127.47))
        bezierPath.addCurve(to: CGPoint(x: 1434.21, y: 1027.49), controlPoint1: CGPoint(x: 1425.88, y: 1061.69), controlPoint2: CGPoint(x: 1433.53, y: 1028.24))
        bezierPath.addCurve(to: CGPoint(x: 1451.68, y: 1026.52), controlPoint1: CGPoint(x: 1434.51, y: 1027.27), controlPoint2: CGPoint(x: 1442.31, y: 1026.82))
        bezierPath.addCurve(to: CGPoint(x: 1676.16, y: 968.47), controlPoint1: CGPoint(x: 1542.13, y: 1023.82), controlPoint2: CGPoint(x: 1620.88, y: 1003.42))
        bezierPath.addCurve(to: CGPoint(x: 1784.08, y: 782.17), controlPoint1: CGPoint(x: 1742.23, y: 926.69), controlPoint2: CGPoint(x: 1777.93, y: 864.97))
        bezierPath.addCurve(to: CGPoint(x: 1783.26, y: 756.52), controlPoint1: CGPoint(x: 1785.21, y: 766.87), controlPoint2: CGPoint(x: 1785.06, y: 761.84))
        bezierPath.addCurve(to: CGPoint(x: 1749.88, y: 700.04), controlPoint1: CGPoint(x: 1778.53, y: 742.19), controlPoint2: CGPoint(x: 1763.98, y: 717.67))
        bezierPath.addCurve(to: CGPoint(x: 1691.83, y: 645.37), controlPoint1: CGPoint(x: 1736.61, y: 683.47), controlPoint2: CGPoint(x: 1712.23, y: 660.52))
        bezierPath.addCurve(to: CGPoint(x: 1503.96, y: 562.19), controlPoint1: CGPoint(x: 1643.91, y: 609.89), controlPoint2: CGPoint(x: 1576.63, y: 580.12))
        bezierPath.addLine(to: CGPoint(x: 1494.13, y: 559.79))
        bezierPath.addLine(to: CGPoint(x: 1493.23, y: 544.79))
        bezierPath.addCurve(to: CGPoint(x: 1437.88, y: 235.49), controlPoint1: CGPoint(x: 1486.26, y: 431.24), controlPoint2: CGPoint(x: 1466.61, y: 321.22))
        bezierPath.addCurve(to: CGPoint(x: 1326.36, y: 50.84), controlPoint1: CGPoint(x: 1408.03, y: 146.54), controlPoint2: CGPoint(x: 1367.16, y: 78.82))
        bezierPath.addCurve(to: CGPoint(x: 1212.21, y: 22.27), controlPoint1: CGPoint(x: 1303.33, y: 35.02), controlPoint2: CGPoint(x: 1269.06, y: 26.47))
        bezierPath.addCurve(to: CGPoint(x: 1084.78, y: 24.29), controlPoint1: CGPoint(x: 1184.23, y: 20.24), controlPoint2: CGPoint(x: 1122.06, y: 21.22))
        bezierPath.addLine(to: CGPoint(x: 1072.18, y: 25.34))
        bezierPath.addLine(to: CGPoint(x: 1061.53, y: 22.79))
        bezierPath.addCurve(to: CGPoint(x: 888.21, y: 0.67), controlPoint1: CGPoint(x: 1010.53, y: 10.57), controlPoint2: CGPoint(x: 948.96, y: 2.69))
        bezierPath.addCurve(to: CGPoint(x: 835.71, y: 0.74), controlPoint1: CGPoint(x: 863.91, y: -0.16), controlPoint2: CGPoint(x: 860.61, y: -0.16))
        bezierPath.close()
        bezierPath.move(to: CGPoint(x: 482.53, y: 511.87))
        bezierPath.addCurve(to: CGPoint(x: 654.96, y: 562.34), controlPoint1: CGPoint(x: 528.51, y: 528.59), controlPoint2: CGPoint(x: 595.33, y: 548.17))
        bezierPath.addCurve(to: CGPoint(x: 1064.08, y: 617.92), controlPoint1: CGPoint(x: 790.78, y: 594.67), controlPoint2: CGPoint(x: 925.33, y: 612.97))
        bezierPath.addCurve(to: CGPoint(x: 1191.96, y: 617.92), controlPoint1: CGPoint(x: 1090.93, y: 618.89), controlPoint2: CGPoint(x: 1166.16, y: 618.89))
        bezierPath.addCurve(to: CGPoint(x: 1473.58, y: 585.22), controlPoint1: CGPoint(x: 1292.53, y: 614.17), controlPoint2: CGPoint(x: 1382.16, y: 603.74))
        bezierPath.addCurve(to: CGPoint(x: 1497.36, y: 580.64), controlPoint1: CGPoint(x: 1486.56, y: 582.59), controlPoint2: CGPoint(x: 1497.21, y: 580.57))
        bezierPath.addCurve(to: CGPoint(x: 1500.73, y: 688.42), controlPoint1: CGPoint(x: 1497.51, y: 580.79), controlPoint2: CGPoint(x: 1500.21, y: 665.99))
        bezierPath.addLine(to: CGPoint(x: 1500.96, y: 696.97))
        bezierPath.addLine(to: CGPoint(x: 1489.33, y: 699.82))
        bezierPath.addCurve(to: CGPoint(x: 1178.46, y: 744.22), controlPoint1: CGPoint(x: 1401.58, y: 721.19), controlPoint2: CGPoint(x: 1287.21, y: 737.54))
        bezierPath.addCurve(to: CGPoint(x: 1058.08, y: 747.29), controlPoint1: CGPoint(x: 1135.33, y: 746.92), controlPoint2: CGPoint(x: 1119.88, y: 747.29))
        bezierPath.addCurve(to: CGPoint(x: 938.83, y: 744.22), controlPoint1: CGPoint(x: 996.21, y: 747.29), controlPoint2: CGPoint(x: 980.98, y: 746.92))
        bezierPath.addCurve(to: CGPoint(x: 470.23, y: 645.29), controlPoint1: CGPoint(x: 771.13, y: 733.64), controlPoint2: CGPoint(x: 609.43, y: 699.52))
        bezierPath.addCurve(to: CGPoint(x: 461.31, y: 639.74), controlPoint1: CGPoint(x: 461.38, y: 641.84), controlPoint2: CGPoint(x: 460.93, y: 641.54))
        bezierPath.addCurve(to: CGPoint(x: 467.91, y: 573.44), controlPoint1: CGPoint(x: 461.53, y: 638.69), controlPoint2: CGPoint(x: 464.46, y: 608.84))
        bezierPath.addCurve(to: CGPoint(x: 474.66, y: 509.17), controlPoint1: CGPoint(x: 471.36, y: 538.12), controlPoint2: CGPoint(x: 474.43, y: 509.17))
        bezierPath.addCurve(to: CGPoint(x: 482.53, y: 511.87), controlPoint1: CGPoint(x: 474.96, y: 509.17), controlPoint2: CGPoint(x: 478.48, y: 510.37))
        bezierPath.close()
        bezierPath.move(to: CGPoint(x: 585.21, y: 915.97))
        bezierPath.addCurve(to: CGPoint(x: 732.21, y: 946.94), controlPoint1: CGPoint(x: 622.63, y: 924.89), controlPoint2: CGPoint(x: 705.96, y: 942.44))
        bezierPath.addCurve(to: CGPoint(x: 719.83, y: 947.54), controlPoint1: CGPoint(x: 734.76, y: 947.32), controlPoint2: CGPoint(x: 731.01, y: 947.54))
        bezierPath.addCurve(to: CGPoint(x: 696.21, y: 948.97), controlPoint1: CGPoint(x: 707.53, y: 947.54), controlPoint2: CGPoint(x: 701.91, y: 947.92))
        bezierPath.addCurve(to: CGPoint(x: 639.58, y: 965.92), controlPoint1: CGPoint(x: 678.81, y: 952.12), controlPoint2: CGPoint(x: 653.83, y: 959.62))
        bezierPath.addCurve(to: CGPoint(x: 611.46, y: 972.14), controlPoint1: CGPoint(x: 627.36, y: 971.32), controlPoint2: CGPoint(x: 625.48, y: 971.77))
        bezierPath.addCurve(to: CGPoint(x: 583.71, y: 974.47), controlPoint1: CGPoint(x: 604.41, y: 972.37), controlPoint2: CGPoint(x: 591.96, y: 973.42))
        bezierPath.addCurve(to: CGPoint(x: 556.41, y: 976.12), controlPoint1: CGPoint(x: 567.06, y: 976.49), controlPoint2: CGPoint(x: 557.98, y: 977.09))
        bezierPath.addCurve(to: CGPoint(x: 561.21, y: 929.92), controlPoint1: CGPoint(x: 554.68, y: 974.99), controlPoint2: CGPoint(x: 556.48, y: 957.82))
        bezierPath.addCurve(to: CGPoint(x: 564.81, y: 911.17), controlPoint1: CGPoint(x: 563.91, y: 914.09), controlPoint2: CGPoint(x: 564.51, y: 911.17))
        bezierPath.addCurve(to: CGPoint(x: 585.21, y: 915.97), controlPoint1: CGPoint(x: 564.88, y: 911.17), controlPoint2: CGPoint(x: 574.11, y: 913.34))
        bezierPath.close()
        bezierPath.move(to: CGPoint(x: 823.93, y: 962.92))
        bezierPath.addCurve(to: CGPoint(x: 984.21, y: 986.24), controlPoint1: CGPoint(x: 861.28, y: 969.14), controlPoint2: CGPoint(x: 935.16, y: 979.94))
        bezierPath.addCurve(to: CGPoint(x: 1011.36, y: 991.34), controlPoint1: CGPoint(x: 1007.16, y: 989.24), controlPoint2: CGPoint(x: 1009.11, y: 989.62))
        bezierPath.addCurve(to: CGPoint(x: 1017.21, y: 995.77), controlPoint1: CGPoint(x: 1012.63, y: 992.39), controlPoint2: CGPoint(x: 1015.26, y: 994.42))
        bezierPath.addCurve(to: CGPoint(x: 1020.43, y: 999.14), controlPoint1: CGPoint(x: 1019.08, y: 997.19), controlPoint2: CGPoint(x: 1020.58, y: 998.69))
        bezierPath.addCurve(to: CGPoint(x: 995.83, y: 1010.47), controlPoint1: CGPoint(x: 1019.91, y: 1000.94), controlPoint2: CGPoint(x: 1003.03, y: 1008.67))
        bezierPath.addCurve(to: CGPoint(x: 930.43, y: 1009.72), controlPoint1: CGPoint(x: 976.93, y: 1015.19), controlPoint2: CGPoint(x: 946.78, y: 1014.82))
        bezierPath.addCurve(to: CGPoint(x: 908.98, y: 998.39), controlPoint1: CGPoint(x: 918.81, y: 1006.04), controlPoint2: CGPoint(x: 908.53, y: 1000.64))
        bezierPath.addCurve(to: CGPoint(x: 913.71, y: 994.04), controlPoint1: CGPoint(x: 909.13, y: 997.72), controlPoint2: CGPoint(x: 911.23, y: 995.77))
        bezierPath.addCurve(to: CGPoint(x: 918.21, y: 988.79), controlPoint1: CGPoint(x: 917.38, y: 991.49), controlPoint2: CGPoint(x: 918.21, y: 990.52))
        bezierPath.addCurve(to: CGPoint(x: 917.08, y: 986.09), controlPoint1: CGPoint(x: 918.21, y: 987.67), controlPoint2: CGPoint(x: 917.68, y: 986.47))
        bezierPath.addCurve(to: CGPoint(x: 813.96, y: 961.94), controlPoint1: CGPoint(x: 914.46, y: 984.67), controlPoint2: CGPoint(x: 845.53, y: 968.54))
        bezierPath.addCurve(to: CGPoint(x: 823.93, y: 962.92), controlPoint1: CGPoint(x: 805.11, y: 960.07), controlPoint2: CGPoint(x: 809.98, y: 960.52))
        bezierPath.close()
        bezierPath.move(to: CGPoint(x: 761.08, y: 989.17))
        bezierPath.addCurve(to: CGPoint(x: 860.46, y: 1001.24), controlPoint1: CGPoint(x: 804.06, y: 990.97), controlPoint2: CGPoint(x: 833.83, y: 994.57))
        bezierPath.addCurve(to: CGPoint(x: 890.83, y: 1012.64), controlPoint1: CGPoint(x: 871.11, y: 1003.94), controlPoint2: CGPoint(x: 878.23, y: 1006.57))
        bezierPath.addCurve(to: CGPoint(x: 923.38, y: 1026.37), controlPoint1: CGPoint(x: 906.66, y: 1020.14), controlPoint2: CGPoint(x: 914.68, y: 1023.52))
        bezierPath.addCurve(to: CGPoint(x: 1003.41, y: 1027.34), controlPoint1: CGPoint(x: 950.91, y: 1035.22), controlPoint2: CGPoint(x: 978.28, y: 1035.59))
        bezierPath.addCurve(to: CGPoint(x: 1023.66, y: 1018.72), controlPoint1: CGPoint(x: 1007.31, y: 1026.07), controlPoint2: CGPoint(x: 1016.38, y: 1022.17))
        bezierPath.addCurve(to: CGPoint(x: 1073.98, y: 1000.42), controlPoint1: CGPoint(x: 1042.86, y: 1009.64), controlPoint2: CGPoint(x: 1056.13, y: 1004.77))
        bezierPath.addLine(to: CGPoint(x: 1082.68, y: 998.32))
        bezierPath.addLine(to: CGPoint(x: 1093.86, y: 999.59))
        bezierPath.addLine(to: CGPoint(x: 1104.96, y: 1000.87))
        bezierPath.addLine(to: CGPoint(x: 1098.96, y: 1001.77))
        bezierPath.addCurve(to: CGPoint(x: 1051.33, y: 1014.44), controlPoint1: CGPoint(x: 1084.78, y: 1004.02), controlPoint2: CGPoint(x: 1066.03, y: 1008.97))
        bezierPath.addCurve(to: CGPoint(x: 1030.03, y: 1023.82), controlPoint1: CGPoint(x: 1047.43, y: 1015.87), controlPoint2: CGPoint(x: 1037.83, y: 1020.14))
        bezierPath.addCurve(to: CGPoint(x: 969.21, y: 1040.62), controlPoint1: CGPoint(x: 1005.13, y: 1035.52), controlPoint2: CGPoint(x: 989.53, y: 1039.87))
        bezierPath.addCurve(to: CGPoint(x: 901.33, y: 1024.79), controlPoint1: CGPoint(x: 945.88, y: 1041.52), controlPoint2: CGPoint(x: 925.18, y: 1036.72))
        bezierPath.addCurve(to: CGPoint(x: 813.58, y: 999.37), controlPoint1: CGPoint(x: 874.56, y: 1011.44), controlPoint2: CGPoint(x: 849.06, y: 1004.02))
        bezierPath.addCurve(to: CGPoint(x: 696.81, y: 992.77), controlPoint1: CGPoint(x: 780.28, y: 995.02), controlPoint2: CGPoint(x: 761.31, y: 993.89))
        bezierPath.addCurve(to: CGPoint(x: 644.31, y: 991.72), controlPoint1: CGPoint(x: 667.78, y: 992.32), controlPoint2: CGPoint(x: 644.16, y: 991.79))
        bezierPath.addCurve(to: CGPoint(x: 690.58, y: 989.17), controlPoint1: CGPoint(x: 644.61, y: 991.49), controlPoint2: CGPoint(x: 676.33, y: 989.77))
        bezierPath.addCurve(to: CGPoint(x: 761.08, y: 989.17), controlPoint1: CGPoint(x: 712.18, y: 988.34), controlPoint2: CGPoint(x: 740.91, y: 988.34))
        bezierPath.close()
        bezierPath.move(to: CGPoint(x: 1384.48, y: 1110.67))
        bezierPath.addCurve(to: CGPoint(x: 1381.26, y: 1192.04), controlPoint1: CGPoint(x: 1384.71, y: 1154.99), controlPoint2: CGPoint(x: 1384.48, y: 1159.87))
        bezierPath.addCurve(to: CGPoint(x: 1339.26, y: 1401.22), controlPoint1: CGPoint(x: 1373.08, y: 1273.04), controlPoint2: CGPoint(x: 1359.73, y: 1339.72))
        bezierPath.addCurve(to: CGPoint(x: 1312.03, y: 1467.14), controlPoint1: CGPoint(x: 1331.61, y: 1424.09), controlPoint2: CGPoint(x: 1316.83, y: 1459.87))
        bezierPath.addCurve(to: CGPoint(x: 1297.18, y: 1480.12), controlPoint1: CGPoint(x: 1308.51, y: 1472.47), controlPoint2: CGPoint(x: 1303.71, y: 1476.59))
        bezierPath.addCurve(to: CGPoint(x: 1262.83, y: 1492.79), controlPoint1: CGPoint(x: 1290.66, y: 1483.49), controlPoint2: CGPoint(x: 1270.11, y: 1491.14))
        bezierPath.addCurve(to: CGPoint(x: 1252.03, y: 1497.07), controlPoint1: CGPoint(x: 1255.41, y: 1494.44), controlPoint2: CGPoint(x: 1253.23, y: 1495.34))
        bezierPath.addCurve(to: CGPoint(x: 1228.93, y: 1501.87), controlPoint1: CGPoint(x: 1250.91, y: 1498.64), controlPoint2: CGPoint(x: 1240.48, y: 1500.82))
        bezierPath.addCurve(to: CGPoint(x: 1218.43, y: 1499.47), controlPoint1: CGPoint(x: 1223.23, y: 1502.39), controlPoint2: CGPoint(x: 1223.16, y: 1502.32))
        bezierPath.addCurve(to: CGPoint(x: 1162.33, y: 1461.97), controlPoint1: CGPoint(x: 1208.61, y: 1493.62), controlPoint2: CGPoint(x: 1187.38, y: 1479.37))
        bezierPath.addCurve(to: CGPoint(x: 1056.21, y: 1396.12), controlPoint1: CGPoint(x: 1107.13, y: 1423.49), controlPoint2: CGPoint(x: 1080.96, y: 1407.22))
        bezierPath.addCurve(to: CGPoint(x: 1024.56, y: 1384.72), controlPoint1: CGPoint(x: 1046.23, y: 1391.62), controlPoint2: CGPoint(x: 1031.83, y: 1386.44))
        bezierPath.addCurve(to: CGPoint(x: 1008.06, y: 1390.64), controlPoint1: CGPoint(x: 1018.41, y: 1383.29), controlPoint2: CGPoint(x: 1016.01, y: 1384.12))
        bezierPath.addCurve(to: CGPoint(x: 983.23, y: 1404.67), controlPoint1: CGPoint(x: 999.66, y: 1397.39), controlPoint2: CGPoint(x: 991.93, y: 1401.74))
        bezierPath.addCurve(to: CGPoint(x: 966.96, y: 1407.52), controlPoint1: CGPoint(x: 977.08, y: 1406.77), controlPoint2: CGPoint(x: 974.61, y: 1407.22))
        bezierPath.addCurve(to: CGPoint(x: 919.18, y: 1389.22), controlPoint1: CGPoint(x: 949.48, y: 1408.12), controlPoint2: CGPoint(x: 936.28, y: 1403.09))
        bezierPath.addCurve(to: CGPoint(x: 910.86, y: 1384.04), controlPoint1: CGPoint(x: 915.73, y: 1386.44), controlPoint2: CGPoint(x: 912.36, y: 1384.27))
        bezierPath.addCurve(to: CGPoint(x: 860.83, y: 1401.67), controlPoint1: CGPoint(x: 905.01, y: 1382.92), controlPoint2: CGPoint(x: 881.38, y: 1391.24))
        bezierPath.addCurve(to: CGPoint(x: 740.68, y: 1479.22), controlPoint1: CGPoint(x: 841.18, y: 1411.64), controlPoint2: CGPoint(x: 841.56, y: 1411.42))
        bezierPath.addLine(to: CGPoint(x: 706.33, y: 1502.24))
        bezierPath.addLine(to: CGPoint(x: 702.43, y: 1501.72))
        bezierPath.addCurve(to: CGPoint(x: 677.01, y: 1496.54), controlPoint1: CGPoint(x: 693.13, y: 1500.59), controlPoint2: CGPoint(x: 678.13, y: 1497.52))
        bezierPath.addCurve(to: CGPoint(x: 674.98, y: 1495.42), controlPoint1: CGPoint(x: 676.41, y: 1495.94), controlPoint2: CGPoint(x: 675.43, y: 1495.42))
        bezierPath.addCurve(to: CGPoint(x: 642.96, y: 1484.92), controlPoint1: CGPoint(x: 671.91, y: 1495.42), controlPoint2: CGPoint(x: 649.26, y: 1487.99))
        bezierPath.addCurve(to: CGPoint(x: 630.96, y: 1479.59), controlPoint1: CGPoint(x: 638.83, y: 1482.89), controlPoint2: CGPoint(x: 633.43, y: 1480.49))
        bezierPath.addCurve(to: CGPoint(x: 618.96, y: 1471.42), controlPoint1: CGPoint(x: 625.03, y: 1477.42), controlPoint2: CGPoint(x: 621.36, y: 1474.94))
        bezierPath.addCurve(to: CGPoint(x: 610.71, y: 1454.69), controlPoint1: CGPoint(x: 617.91, y: 1469.92), controlPoint2: CGPoint(x: 614.16, y: 1462.34))
        bezierPath.addCurve(to: CGPoint(x: 546.51, y: 1178.92), controlPoint1: CGPoint(x: 577.41, y: 1381.27), controlPoint2: CGPoint(x: 556.71, y: 1292.17))
        bezierPath.addCurve(to: CGPoint(x: 545.08, y: 1075.57), controlPoint1: CGPoint(x: 544.41, y: 1155.82), controlPoint2: CGPoint(x: 543.73, y: 1106.62))
        bezierPath.addCurve(to: CGPoint(x: 546.51, y: 1049.69), controlPoint1: CGPoint(x: 545.61, y: 1063.49), controlPoint2: CGPoint(x: 546.21, y: 1051.87))
        bezierPath.addLine(to: CGPoint(x: 546.96, y: 1045.79))
        bezierPath.addLine(to: CGPoint(x: 550.48, y: 1049.39))
        bezierPath.addCurve(to: CGPoint(x: 568.56, y: 1084.04), controlPoint1: CGPoint(x: 554.76, y: 1053.74), controlPoint2: CGPoint(x: 562.48, y: 1068.52))
        bezierPath.addCurve(to: CGPoint(x: 582.88, y: 1125.82), controlPoint1: CGPoint(x: 570.81, y: 1089.82), controlPoint2: CGPoint(x: 577.26, y: 1108.64))
        bezierPath.addCurve(to: CGPoint(x: 603.51, y: 1180.94), controlPoint1: CGPoint(x: 593.91, y: 1159.57), controlPoint2: CGPoint(x: 597.88, y: 1170.22))
        bezierPath.addCurve(to: CGPoint(x: 640.41, y: 1214.17), controlPoint1: CGPoint(x: 614.16, y: 1201.04), controlPoint2: CGPoint(x: 624.43, y: 1210.34))
        bezierPath.addCurve(to: CGPoint(x: 783.58, y: 1223.69), controlPoint1: CGPoint(x: 667.71, y: 1220.54), controlPoint2: CGPoint(x: 723.81, y: 1224.29))
        bezierPath.addCurve(to: CGPoint(x: 821.31, y: 1222.12), controlPoint1: CGPoint(x: 810.36, y: 1223.47), controlPoint2: CGPoint(x: 817.11, y: 1223.17))
        bezierPath.addCurve(to: CGPoint(x: 903.06, y: 1149.52), controlPoint1: CGPoint(x: 854.76, y: 1214.09), controlPoint2: CGPoint(x: 876.66, y: 1194.67))
        bezierPath.addCurve(to: CGPoint(x: 921.96, y: 1114.64), controlPoint1: CGPoint(x: 906.58, y: 1143.52), controlPoint2: CGPoint(x: 915.13, y: 1127.77))
        bezierPath.addCurve(to: CGPoint(x: 948.58, y: 1072.87), controlPoint1: CGPoint(x: 936.88, y: 1086.14), controlPoint2: CGPoint(x: 942.51, y: 1077.37))
        bezierPath.addCurve(to: CGPoint(x: 975.06, y: 1069.64), controlPoint1: CGPoint(x: 956.83, y: 1066.79), controlPoint2: CGPoint(x: 966.28, y: 1065.59))
        bezierPath.addCurve(to: CGPoint(x: 1005.51, y: 1112.02), controlPoint1: CGPoint(x: 984.28, y: 1073.84), controlPoint2: CGPoint(x: 990.81, y: 1082.92))
        bezierPath.addCurve(to: CGPoint(x: 1067.16, y: 1202.62), controlPoint1: CGPoint(x: 1029.36, y: 1159.27), controlPoint2: CGPoint(x: 1047.58, y: 1186.12))
        bezierPath.addCurve(to: CGPoint(x: 1106.83, y: 1222.12), controlPoint1: CGPoint(x: 1080.66, y: 1214.09), controlPoint2: CGPoint(x: 1091.23, y: 1219.27))
        bezierPath.addCurve(to: CGPoint(x: 1220.08, y: 1222.42), controlPoint1: CGPoint(x: 1120.93, y: 1224.67), controlPoint2: CGPoint(x: 1187.08, y: 1224.82))
        bezierPath.addCurve(to: CGPoint(x: 1291.18, y: 1213.34), controlPoint1: CGPoint(x: 1245.43, y: 1220.54), controlPoint2: CGPoint(x: 1280.46, y: 1216.12))
        bezierPath.addCurve(to: CGPoint(x: 1326.43, y: 1178.54), controlPoint1: CGPoint(x: 1305.73, y: 1209.67), controlPoint2: CGPoint(x: 1315.93, y: 1199.54))
        bezierPath.addCurve(to: CGPoint(x: 1347.58, y: 1121.17), controlPoint1: CGPoint(x: 1332.21, y: 1166.92), controlPoint2: CGPoint(x: 1336.03, y: 1156.42))
        bezierPath.addCurve(to: CGPoint(x: 1367.53, y: 1066.94), controlPoint1: CGPoint(x: 1359.06, y: 1086.22), controlPoint2: CGPoint(x: 1362.13, y: 1077.82))
        bezierPath.addCurve(to: CGPoint(x: 1380.73, y: 1046.02), controlPoint1: CGPoint(x: 1371.36, y: 1059.29), controlPoint2: CGPoint(x: 1378.03, y: 1048.72))
        bezierPath.addLine(to: CGPoint(x: 1382.46, y: 1044.29))
        bezierPath.addLine(to: CGPoint(x: 1383.43, y: 1055.92))
        bezierPath.addCurve(to: CGPoint(x: 1384.48, y: 1110.67), controlPoint1: CGPoint(x: 1383.96, y: 1063.04), controlPoint2: CGPoint(x: 1384.41, y: 1084.19))
        bezierPath.close()
        bezierPath.move(to: CGPoint(x: 980.08, y: 1528.34))
        bezierPath.addCurve(to: CGPoint(x: 1048.33, y: 1567.12), controlPoint1: CGPoint(x: 1001.61, y: 1542.37), controlPoint2: CGPoint(x: 1022.16, y: 1553.99))
        bezierPath.addCurve(to: CGPoint(x: 1181.83, y: 1619.47), controlPoint1: CGPoint(x: 1093.93, y: 1589.92), controlPoint2: CGPoint(x: 1145.98, y: 1610.39))
        bezierPath.addCurve(to: CGPoint(x: 1194.21, y: 1623.74), controlPoint1: CGPoint(x: 1190.68, y: 1621.72), controlPoint2: CGPoint(x: 1194.21, y: 1622.92))
        bezierPath.addCurve(to: CGPoint(x: 1146.81, y: 1641.59), controlPoint1: CGPoint(x: 1194.21, y: 1626.89), controlPoint2: CGPoint(x: 1165.41, y: 1637.77))
        bezierPath.addCurve(to: CGPoint(x: 1085.76, y: 1639.49), controlPoint1: CGPoint(x: 1124.53, y: 1646.17), controlPoint2: CGPoint(x: 1103.16, y: 1645.42))
        bezierPath.addCurve(to: CGPoint(x: 1041.81, y: 1619.69), controlPoint1: CGPoint(x: 1077.43, y: 1636.64), controlPoint2: CGPoint(x: 1070.61, y: 1633.57))
        bezierPath.addCurve(to: CGPoint(x: 1012.48, y: 1605.74), controlPoint1: CGPoint(x: 1028.53, y: 1613.24), controlPoint2: CGPoint(x: 1015.33, y: 1607.02))
        bezierPath.addCurve(to: CGPoint(x: 967.18, y: 1600.64), controlPoint1: CGPoint(x: 1001.91, y: 1601.09), controlPoint2: CGPoint(x: 1000.56, y: 1600.94))
        bezierPath.addCurve(to: CGPoint(x: 882.43, y: 1621.57), controlPoint1: CGPoint(x: 923.46, y: 1600.19), controlPoint2: CGPoint(x: 926.08, y: 1599.52))
        bezierPath.addCurve(to: CGPoint(x: 832.71, y: 1641.89), controlPoint1: CGPoint(x: 854.31, y: 1635.82), controlPoint2: CGPoint(x: 847.63, y: 1638.59))
        bezierPath.addCurve(to: CGPoint(x: 807.96, y: 1643.47), controlPoint1: CGPoint(x: 826.18, y: 1643.32), controlPoint2: CGPoint(x: 823.03, y: 1643.54))
        bezierPath.addCurve(to: CGPoint(x: 768.96, y: 1638.29), controlPoint1: CGPoint(x: 789.43, y: 1643.47), controlPoint2: CGPoint(x: 784.78, y: 1642.87))
        bezierPath.addCurve(to: CGPoint(x: 734.08, y: 1623.82), controlPoint1: CGPoint(x: 755.91, y: 1634.47), controlPoint2: CGPoint(x: 734.08, y: 1625.47))
        bezierPath.addCurve(to: CGPoint(x: 747.81, y: 1619.17), controlPoint1: CGPoint(x: 734.08, y: 1623.44), controlPoint2: CGPoint(x: 740.23, y: 1621.42))
        bezierPath.addCurve(to: CGPoint(x: 949.56, y: 1527.82), controlPoint1: CGPoint(x: 819.43, y: 1598.47), controlPoint2: CGPoint(x: 885.81, y: 1568.39))
        bezierPath.addCurve(to: CGPoint(x: 962.68, y: 1520.17), controlPoint1: CGPoint(x: 955.63, y: 1523.92), controlPoint2: CGPoint(x: 961.56, y: 1520.54))
        bezierPath.addCurve(to: CGPoint(x: 980.08, y: 1528.34), controlPoint1: CGPoint(x: 965.53, y: 1519.42), controlPoint2: CGPoint(x: 968.31, y: 1520.69))
        bezierPath.close()
        fillColor.setFill()
        bezierPath.fill()


        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.move(to: CGPoint(x: 250.71, y: 2111.99))
        bezier2Path.addCurve(to: CGPoint(x: -0.09, y: 2313.29), controlPoint1: CGPoint(x: 112.93, y: 2222.54), controlPoint2: CGPoint(x: 0.06, y: 2313.14))
        bezier2Path.addCurve(to: CGPoint(x: 111.58, y: 2369.54), controlPoint1: CGPoint(x: -0.24, y: 2313.44), controlPoint2: CGPoint(x: 50.01, y: 2338.79))
        bezier2Path.addLine(to: CGPoint(x: 223.56, y: 2425.49))
        bezier2Path.addLine(to: CGPoint(x: 144.88, y: 2477.99))
        bezier2Path.addCurve(to: CGPoint(x: 66.21, y: 2531.02), controlPoint1: CGPoint(x: 101.61, y: 2506.79), controlPoint2: CGPoint(x: 66.21, y: 2530.64))
        bezier2Path.addCurve(to: CGPoint(x: 652.93, y: 3558.82), controlPoint1: CGPoint(x: 66.21, y: 2532.14), controlPoint2: CGPoint(x: 652.63, y: 3559.57))
        bezier2Path.addCurve(to: CGPoint(x: 501.81, y: 1914.44), controlPoint1: CGPoint(x: 653.16, y: 3557.99), controlPoint2: CGPoint(x: 502.63, y: 1919.62))
        bezier2Path.addLine(to: CGPoint(x: 501.21, y: 1910.92))
        bezier2Path.addLine(to: CGPoint(x: 250.71, y: 2111.99))
        bezier2Path.close()
        fillColor.setFill()
        bezier2Path.fill()


        //// Bezier 3 Drawing
        let bezier3Path = UIBezierPath()
        bezier3Path.move(to: CGPoint(x: 1456.71, y: 1914.82))
        bezier3Path.addCurve(to: CGPoint(x: 1305.73, y: 3558.59), controlPoint1: CGPoint(x: 1455.51, y: 1925.09), controlPoint2: CGPoint(x: 1305.58, y: 3557.69))
        bezier3Path.addCurve(to: CGPoint(x: 1892.46, y: 2531.02), controlPoint1: CGPoint(x: 1305.96, y: 3559.57), controlPoint2: CGPoint(x: 1892.46, y: 2532.29))
        bezier3Path.addCurve(to: CGPoint(x: 1813.78, y: 2477.99), controlPoint1: CGPoint(x: 1892.46, y: 2530.72), controlPoint2: CGPoint(x: 1857.06, y: 2506.79))
        bezier3Path.addLine(to: CGPoint(x: 1735.11, y: 2425.49))
        bezier3Path.addLine(to: CGPoint(x: 1847.08, y: 2369.54))
        bezier3Path.addCurve(to: CGPoint(x: 1958.38, y: 2312.99), controlPoint1: CGPoint(x: 1908.66, y: 2338.79), controlPoint2: CGPoint(x: 1958.76, y: 2313.29))
        bezier3Path.addCurve(to: CGPoint(x: 1458.06, y: 1911.52), controlPoint1: CGPoint(x: 1957.86, y: 2312.54), controlPoint2: CGPoint(x: 1462.18, y: 1914.74))
        bezier3Path.addCurve(to: CGPoint(x: 1456.71, y: 1914.82), controlPoint1: CGPoint(x: 1457.46, y: 1910.99), controlPoint2: CGPoint(x: 1457.08, y: 1911.89))
        bezier3Path.close()
        fillColor.setFill()
        bezier3Path.fill()


        //// Bezier 4 Drawing
        let bezier4Path = UIBezierPath()
        bezier4Path.move(to: CGPoint(x: 949.63, y: 2336.17))
        bezier4Path.addCurve(to: CGPoint(x: 896.83, y: 2400.59), controlPoint1: CGPoint(x: 924.81, y: 2342.62), controlPoint2: CGPoint(x: 903.81, y: 2368.27))
        bezier4Path.addCurve(to: CGPoint(x: 904.71, y: 2476.12), controlPoint1: CGPoint(x: 891.21, y: 2426.54), controlPoint2: CGPoint(x: 894.06, y: 2453.92))
        bezier4Path.addCurve(to: CGPoint(x: 920.76, y: 2499.89), controlPoint1: CGPoint(x: 909.73, y: 2486.77), controlPoint2: CGPoint(x: 913.71, y: 2492.54))
        bezier4Path.addCurve(to: CGPoint(x: 1006.71, y: 2499.59), controlPoint1: CGPoint(x: 946.26, y: 2526.29), controlPoint2: CGPoint(x: 981.51, y: 2526.14))
        bezier4Path.addCurve(to: CGPoint(x: 1015.18, y: 2364.89), controlPoint1: CGPoint(x: 1038.21, y: 2466.44), controlPoint2: CGPoint(x: 1042.11, y: 2404.64))
        bezier4Path.addCurve(to: CGPoint(x: 976.26, y: 2335.79), controlPoint1: CGPoint(x: 1005.21, y: 2350.04), controlPoint2: CGPoint(x: 990.73, y: 2339.24))
        bezier4Path.addCurve(to: CGPoint(x: 949.63, y: 2336.17), controlPoint1: CGPoint(x: 969.43, y: 2334.22), controlPoint2: CGPoint(x: 956.38, y: 2334.37))
        bezier4Path.close()
        fillColor.setFill()
        bezier4Path.fill()


        //// Bezier 5 Drawing
        let bezier5Path = UIBezierPath()
        bezier5Path.move(to: CGPoint(x: 950.61, y: 2757.74))
        bezier5Path.addCurve(to: CGPoint(x: 907.71, y: 2793.29), controlPoint1: CGPoint(x: 933.43, y: 2761.94), controlPoint2: CGPoint(x: 918.58, y: 2774.24))
        bezier5Path.addCurve(to: CGPoint(x: 894.13, y: 2854.79), controlPoint1: CGPoint(x: 898.18, y: 2809.94), controlPoint2: CGPoint(x: 892.93, y: 2834.02))
        bezier5Path.addCurve(to: CGPoint(x: 948.58, y: 2939.32), controlPoint1: CGPoint(x: 896.61, y: 2897.02), controlPoint2: CGPoint(x: 917.76, y: 2929.79))
        bezier5Path.addCurve(to: CGPoint(x: 978.58, y: 2939.24), controlPoint1: CGPoint(x: 956.68, y: 2941.79), controlPoint2: CGPoint(x: 970.56, y: 2941.79))
        bezier5Path.addCurve(to: CGPoint(x: 1018.71, y: 2905.34), controlPoint1: CGPoint(x: 995.16, y: 2934.07), controlPoint2: CGPoint(x: 1008.73, y: 2922.59))
        bezier5Path.addCurve(to: CGPoint(x: 999.66, y: 2769.44), controlPoint1: CGPoint(x: 1043.91, y: 2861.77), controlPoint2: CGPoint(x: 1034.91, y: 2797.57))
        bezier5Path.addCurve(to: CGPoint(x: 975.06, y: 2757.37), controlPoint1: CGPoint(x: 992.98, y: 2764.12), controlPoint2: CGPoint(x: 982.63, y: 2759.02))
        bezier5Path.addCurve(to: CGPoint(x: 950.61, y: 2757.74), controlPoint1: CGPoint(x: 967.93, y: 2755.79), controlPoint2: CGPoint(x: 957.88, y: 2755.94))
        bezier5Path.close()
        fillColor.setFill()
        bezier5Path.fill()


        //// Oval Drawing
        context.saveGState()
        context.translateBy(x: 964.1, y: 3270.49)
        context.rotate(by: -0.3 * CGFloat.pi/180)

        let ovalPath = UIBezierPath(ovalIn: CGRect(x: -70.15, y: -92.6, width: 140.3, height: 185.2))
        fillColor.setFill()
        ovalPath.fill()

        context.restoreGState()
        
        context.restoreGState()

    }




    @objc(StylishSpyResizingBehavior)
    public enum ResizingBehavior: Int {
        case aspectFit /// The content is proportionally resized to fit into the target rectangle.
        case aspectFill /// The content is proportionally resized to completely fill the target rectangle.
        case stretch /// The content is stretched to match the entire target rectangle.
        case center /// The content is centered in the target rectangle, but it is NOT resized.

        public func apply(rect: CGRect, target: CGRect) -> CGRect {
            if rect == target || target == CGRect.zero {
                return rect
            }

            var scales = CGSize.zero
            scales.width = abs(target.width / rect.width)
            scales.height = abs(target.height / rect.height)

            switch self {
                case .aspectFit:
                    scales.width = min(scales.width, scales.height)
                    scales.height = scales.width
                case .aspectFill:
                    scales.width = max(scales.width, scales.height)
                    scales.height = scales.width
                case .stretch:
                    break
                case .center:
                    scales.width = 1
                    scales.height = 1
            }

            var result = rect.standardized
            result.size.width *= scales.width
            result.size.height *= scales.height
            result.origin.x = target.minX + (target.width - result.width) / 2
            result.origin.y = target.minY + (target.height - result.height) / 2
            return result
        }
    }
}
